### PR TITLE
Update 'embedded-hal' to '1'

### PR DESCRIPTION
**Pull request by ne0h**

### CODE REVIEW

**Review by jgosmann — CHANGES_REQUESTED** [review]
Thank you! I finally got around to have a quick look. The changes so far look good to me, but it seems that some necessary updates in `src/bme.rs` have been missed. I get a compilation error when I try to run the tests:

```
❯ cargo test --features test-support                                                                                              9a469c8
    Updating git repository `https://github.com/nand-nor/bme680.git`
    Updating crates.io index
  Downloaded embedded-hal v1.0.0
  Downloaded 1 crate (29.8 KB) in 0.25s
   Compiling embedded-hal v1.0.0
   Compiling bme680 v0.7.0 (https://github.com/nand-nor/bme680.git?rev=1e3acb1#1e3acb1c)
   Compiling bsec v0.5.0+1.4.9.2 (/Users/jgosmann/Documents/projects/weatherstone/bsec)
    Finished test [unoptimized + debuginfo] target(s) in 2.72s
     Running unittests src/lib.rs (target/debug/deps/bsec-decec6feeaa36e55)

running 7 tests
test clock::tests::time_passed_smoke_test ... ok
test tests::get_version_smoke_test ... ok
test tests::reset_output_smoke_test ... ok
test tests::basic_bsec_operation_smoke_test ... ok
test tests::configuration_roundtrip_smoke_test ... ok
test tests::roundtrip_state_smoke_test ... ok
test tests::cannot_create_mulitple_bsec_at_the_same_time ... ok

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests bsec

running 4 tests
test src/bme.rs - bme::BmeSensor (line 20) ... FAILED
test src/clock.rs - clock::Clock (line 12) ... ok
test src/clock.rs - clock::test_support::FakeClock (line 96) ... ok
test src/lib.rs - (line 87) ... ok

failures:

---- src/bme.rs - bme::BmeSensor (line 20) stdout ----
error[E0433]: failed to resolve: could not find `blocking` in `embedded_hal`
 --> src/bme.rs:25:19
  |
8 | use embedded_hal::blocking::{delay::DelayMs, i2c};
  |                   ^^^^^^^^ could not find `blocking` in `embedded_hal`

error[E0432]: unresolved import `embedded_hal::blocking`
 --> src/bme.rs:25:19
  |
8 | use embedded_hal::blocking::{delay::DelayMs, i2c};
  |                   ^^^^^^^^ could not find `blocking` in `embedded_hal`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
Couldn't compile the test.

failures:
    src/bme.rs - bme::BmeSensor (line 20)

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.32s

error: doctest failed, to rerun pass `--doc`
```

**Comment by ne0h** [comment]
Thanks for having a look! I fixed the example code from `bme.rs`. Tests are running on my machine.

**Comment by jgosmann** [comment]
Looks good to me now. I'll do some testing with actual hardware over the weekend before merging.

Given that marcelbuesing/bme680 looks pretty unmaintained, I wonder whether it would be beneficial to migrate to JakobLachermeier/bosch-bme680 which has recent releases and support for `embedded-hal` 1, but little stars/contributors. 🤔

**Review by jgosmann — APPROVED** [review]

**Comment by jgosmann** [comment]
Apparently it is not possible to publish a crate with a dependency using a `git` version specifier. Thus, a `bsec` release is blocked until either that upstream PR is merged, we have a published fork with that PR, or migrate to JakobLachermeier/bosch-bme680.

**Comment by ne0h** [comment]
I left another comment in https://github.com/marcelbuesing/bme680/pull/52. I would prefer not touching the dependencies wrt. the bme680 driver as long there is another option.

Did you intentionally prepare a release of `0.6.0` after `0.3.1`?

UPDATE: @jgosmann, looks like we were unblocked.

**Comment by jgosmann** [comment]
> Did you intentionally prepare a release of 0.6.0 after 0.3.1?

Seems like I forgot to create some releases in GitHub, but the last release was 0.5.0.

> UPDATE: @jgosmann, looks like we were unblocked.

Not until there is an actual release, but great to see that things are moving.

**Comment by jgosmann** [comment]
I created the missing releases in GitHub.

**Pull request merged**
